kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: devops
    - name: trainer
      value:  shivakumar
    - name: duration
      value: 120hrs   